dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
script:
  - py.test  --cov-report term --cov=app/test/
after_success:
  - codecov
